<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-question.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for 물음 page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 대답',
		'a_convert_to_c_on' => 'Convert this answer into a comment on:',
		'a_convert_to_c' => 'Convert this answer into a comment',
		'a_convert_warn_cs' => 'Warning: This conversion cannot be reversed and will also move this answer\'s comments.',
		'a_convert_warn' => 'Warning: This conversion cannot be reversed.',
		'a_notify_email' => 'Email me at this address if my answer is selected or commented on:',
		'a_notify_label' => 'Email me if my answer is selected or commented on',
		'a_notify_x_label' => 'Email me (^) if my answer is selected or commented on',
		'a_waiting_your_approval' => 'This answer is waiting for your approval',
		'a_your_waiting_approval' => 'Your answer will be checked and approved shortly.',
		'add_answer_button' => '대답 더하기',
		'add_comment_button' => 'Add comment',
		'add_q_favorites' => 'Add this 물음 to my favorites',
		'anon_name_label' => '표시할 이름 (선택사항):',
		'answer_button' => '대답',
		'answer_limit' => 'Too many answers received - please try again in an hour',
		'answer_must_be_approved' => 'Your account must be approved before you answer a 물음.',
		'answer_must_confirm' => 'Please ^5confirm your email address^6 to answer this 물음.',
		'answer_must_login' => 'Please ^1log in^2 or ^3register^4 to answer this 물음.',
		'answer_q_popup' => '물음에 대답',
		'approve_button' => 'approve',
		'ask_button' => '물어보기',
		'ask_follow_from_a' => 'Your 물음 will be related to this answer:',
		'ask_follow_title' => 'Ask a related 물음',
		'ask_limit' => 'Too many 물음s received - please try again in an hour',
		'ask_must_be_approved' => 'Your account must be approved before you ask a 물음.',
		'ask_must_confirm' => 'Please ^5confirm your email address^6 to ask a 물음.',
		'ask_must_login' => 'Please ^1log in^2 or ^3register^4 to ask a 물음.',
		'ask_same_q' => 'Before proceeding, please check your 물음 was not asked already:',
		'ask_title' => '물어보기',
		'c_notify_email' => 'Email me at this address if a comment is added after mine:',
		'c_notify_label' => 'Email me if a comment is added after mine',
		'c_notify_x_label' => 'Email me (^) if a comment is added after mine',
		'c_waiting_your_approval' => 'This comment is waiting for your approval',
		'c_your_waiting_approval' => 'Your comment will be checked and approved shortly.',
		'category_js_note' => 'To select any category, please enable Javascript in your web browser.',
		'category_required' => 'Please choose a category',
		'category_ask_not_allowed' => 'You do not have permission to ask 물음s in this category',
		'claim_button' => 'I wrote this',
		'clear_flags_button' => 'clear flags',
		'clear_flags_popup' => 'Remove flags by all users',
		'close_button' => 'close',
		'close_duplicate_error' => 'The duplicate 물음 could not be found - please try entering the number from a different 물음 URL, e.g. 123.',
		'close_duplicate' => 'This is a duplicate of another 물음',
		'close_form_button' => 'Close 물음',
		'close_form_title' => 'Close this 물음',
		'close_original_note' => 'You can also enter the 물음 number from the URL, e.g. 123.',
		'close_original_title' => 'URL of the original 물음:',
		'close_q_popup' => 'Close this 물음 to any new answers',
		'close_reason_title' => 'Reason for closing this 물음:',
		'closed_as_duplicate' => 'closed as a duplicate of:',
		'closed_with_note' => 'closed with the note:',
		'comment_a_popup' => 'Add a comment on this answer',
		'comment_button' => 'comment',
		'comment_limit' => 'Too many comments received - please try again in an hour',
		'comment_must_be_approved' => 'Your account must be approved before you add a comment.',
		'comment_must_confirm' => 'Please ^5confirm your email address^6 to add a comment.',
		'comment_must_login' => 'Please ^1log in^2 or ^3register^4 to add a comment.',
		'comment_on_a' => 'On 대답: ',
		'comment_on_q' => 'On 물음: ',
		'comment_q_popup' => 'Add a comment on this 물음',
		'delete_a_popup' => '지우기',
		'delete_button' => '지우기',
		'delete_c_popup' => 'Delete this comment permanently',
		'delete_q_popup' => 'Delete this 물음 permanently',
		'duplicate_content' => 'Your submission appears to be a duplicate.',
		'edit_a_popup' => '대답 편집',
		'edit_a_title' => '대답 편집',
		'edit_button' => '편집',
		'edit_c_popup' => 'Edit this comment',
		'edit_c_title' => 'Edit comment',
		'edit_must_confirm' => 'Please ^5confirm your email address^6 to edit this.',
		'edit_must_login' => 'Please ^1log in^2 or ^3register^4 to edit this.',
		'edit_q_popup' => 'Edit this 물음',
		'edit_q_title' => 'Edit Question',
		'example_tags' => 'Example tags: ',
		'flag_a_popup' => 'Flag this answer as spam or inappropriate',
		'flag_button' => 'flag',
		'flag_c_popup' => 'Flag this comment as spam or inappropriate',
		'flag_hide_button' => 'flag and hide',
		'flag_limit' => 'Too many posts flagged - please try again in an hour',
		'flag_must_confirm' => 'Please ^5confirm your email address^6 to flag posts.',
		'flag_must_login' => 'Please ^1log in^2 or ^3register^4 to flag posts.',
		'flag_not_allowed' => 'Flagging this is not allowed',
		'flag_q_popup' => 'Flag this 물음 as spam or inappropriate',
		'follow_a_popup' => 'Ask a new 물음 relating to this answer',
		'follow_button' => 'ask related 물음',
		'follows_a' => 'related to an answer for:',
		'follows_q' => 'about the 물음:',
		'hide_a_popup' => 'Hide this answer',
		'hide_button' => '숨기기',
		'hide_c_popup' => 'Hide this comment',
		'hide_q_popup' => '물음 숨기기',
		'matching_tags' => 'Matching tags: ',
		'max_tags_x' => 'A maximum of ^ tags are allowed',
		'min_tags_x' => 'Please provide at least ^ tag/s',
		'notify_email_note' => '사생활: email 주소는 공유되거나 다른곳에 팔리지 않습니다.',
		'q_category_label' => 'Category:',
		'q_content_label' => '물음에 대한 자세한 정보:',
		'q_hidden_author' => 'This 물음 has been hidden by its author',
		'q_hidden_flagged' => 'This 물음 has been flagged and hidden',
		'q_hidden_other' => 'This 물음 has been hidden',
		'q_notify_email' => 'Email me at this address if my 물음 is answered or commented on:',
		'q_notify_label' => 'Email me if my 물음 is answered or commented on',
		'q_notify_x_label' => 'Email me (^) if my 물음 is answered or commented on',
		'q_tags_comma_label' => 'Tags - use comma (,) as a separator:',
		'q_tags_label' => 'Tags - use hyphens to combine words:',
		'q_title_label' => '물음을 한 문장으로:',
		'q_waiting_approval' => 'This 물음 is waiting for approval',
		'q_waiting_your_approval' => 'This 물음 is waiting for your approval',
		'q_your_waiting_approval' => 'Your 물음 will be checked and approved shortly.',
		'recat_button' => 'recategorize',
		'recat_popup' => 'Change this 물음\'s category',
		'recat_q_title' => 'Recategorize 물음',
		'reject_button' => 'reject',
		'remove_q_favorites' => 'Remove this 물음 from my favorites',
		'reopen_button' => 'reopen',
		'reply_button' => 'reply',
		'reply_c_popup' => 'Reply to this comment',
		'reshow_button' => 'reshow',
		'retag_button' => 'retag',
		'retag_cat_popup' => 'Change this 물음\'s category or tags',
		'retag_popup' => 'Change this 물음\'s tags',
		'retag_q_title' => 'Retag 물음',
		'save_silent_label' => 'Save silently to hide that this was edited', 
		'select_popup' => 'Click to select as best answer',
		'select_text' => '가장 좋은 답',
		'show_1_comment' => 'Show 1 comment',
		'show_1_previous_comment' => 'Show 1 previous comment',
		'show_x_comments' => 'Show ^ comments',
		'show_x_previous_comments' => 'Show ^ previous comments',
		'unflag_button' => 'unflag',
		'unflag_popup' => 'Remove the flag that you added',
		'unselect_popup' => 'Click to remove selection',
		'x_answers_title' => '^ 대답',
		'your_answer_title' => '그대의 대답',
		'your_comment_a' => 'Your comment on this 대답:',
		'your_comment_q' => 'Your comment on this 물음:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
